version: '3.7'

services:

  nginxcgi:
    container_name: oml-nginx-cgi
    hostname: nginxcgi
    dns: 8.8.8.8
    image: omnileads/nginxqa:latest
    environment:
      - PGHOST=${PGHOST}
      - PGPASSWORD=${PGPASSWORD}
      - PSTN_HOSTNAME=${PSTN_HOSTNAME}
    networks: 
      - oml_omnileads
    ports:
      - 8888:8888
    privileged: true
    restart: on-failure
    stdin_open: true
    stop_grace_period: 1m30s
    tty: true
    #volumes:
    #  - ./scripts_cgi:/usr/share/nginx/html/

  # pbxemulator:
  #   container_name: oml-pstn-emulator
  #   hostname: pbxemulator
  #   dns: 8.8.8.8
  #   image: omnileads/pstn_emulator:latest
  #   networks:
  #     - oml_omnileads
  #   ports:
  #     - 6060:5060/udp
  #     - 10000-10020:10000-10020/udp
  #   privileged: true
  #   restart: on-failure
  #   stdin_open: true
  #   stop_grace_period: 1m30s
  #   tty: true

networks:
  oml_omnileads:
    external: true
