# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options

class TestReportesLlamadas():
  def setup_method(self, method):
    chromeOptions = Options()
    self.driver = webdriver.Remote(command_executor='http://172.16.102.101:4444/wd/hub', options=chromeOptions)
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_reportesLlamadas(self):
    self.driver.get("https://orionis.fts-cloud.net/accounts/login/")
    self.driver.set_window_size(1440, 877)
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("FTS098098OML")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.XPATH, "//a[contains(@href, \'#menuReports\')]").click()
    self.driver.find_element(By.XPATH, "//ul[@id=\'menuReports\']/li/a").click()
    self.driver.find_element(By.ID, "id_finalizadas").click()
    self.driver.find_element(By.ID, "id_buscar_btn").click()
    self.driver.find_element(By.CSS_SELECTOR, "h2:nth-child(4)").click()
    self.driver.find_element(By.XPATH, "//ul[@id=\'menuReports\']/li[2]/a").click()
    self.driver.find_element(By.ID, "id_fecha").click()
    self.driver.find_element(By.CSS_SELECTOR, "ul > .active").click()
    self.driver.find_element(By.ID, "id_todos_agentes").click()
    self.driver.find_element(By.ID, "id_buscar_btn").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(3) > h2").click()
    self.driver.find_element(By.CSS_SELECTOR, ".wrapper-table > .wrapper-table th:nth-child(1)").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.XPATH, "//a[contains(@href, \'/reportes/agentes_export/tiempos_agentes/\')]").click()
    self.vars["win1762"] = self.wait_for_window(2000)
    self.driver.find_element(By.CSS_SELECTOR, ".wrapper-info > h1").click()
    self.driver.find_element(By.XPATH, "//a[contains(@href, \'/accounts/logout/\')]").click()
  
