# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options

class TestLoginLogoutAgente():
  def setup_method(self, method):
    chromeOptions = Options()
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', options=chromeOptions)
    self.vars = {}


  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loginLogoutAgente(self):
    self.driver.get("https://localhost/accounts/login/")
    self.driver.set_window_size(1050, 721)
    self.driver.find_element(By.ID, "id_username").send_keys("agente1")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("098098AAA")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("098098ZZZ")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.ID, "1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".icon-control-pause").click()
    self.driver.find_element(By.ID, "select2-pauseType-container").click()
    self.driver.find_element(By.ID, "setPause").click()
    self.driver.find_element(By.ID, "Resume").click()
    self.driver.find_element(By.CSS_SELECTOR, ".user-name").click()
    self.driver.find_element(By.ID, "logout").click()
  
