# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestModuloGrabaciones():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://172.16.102.101:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_moduloGrabaciones(self):
    self.driver.get("https://orionis.fts-cloud.net/accounts/login/")
    self.driver.set_window_size(1440, 877)
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("FTS098098OML")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.XPATH, "//a[contains(@href, \'/grabacion/buscar/1/\')]").click()
    self.driver.find_element(By.ID, "id_fecha").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ranges .active").click()
    self.driver.find_element(By.ID, "id_buscar_btn").click()
    self.driver.find_element(By.CSS_SELECTOR, "th:nth-child(3)").click()
    self.driver.find_element(By.XPATH, "//a[contains(@href, \'/accounts/logout/\')]").click()
  
