# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options

class TestABMUsuarioSupervisor():
  def setup_method(self, method):
    chromeOptions = Options()
    self.driver = webdriver.Remote(command_executor='http://172.16.102.101:4444/wd/hub', options=chromeOptions)
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()
  
  def test_aBMUsuarioSupervisor(self):
    self.driver.get("https://orionis.fts-cloud.net/accounts/login/")
    self.driver.set_window_size(1440, 877)
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("FTS098098OML")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.XPATH, "//a[contains(@href, \'#menuUsersGroups\')]").click()
    self.driver.find_element(By.XPATH, "//ul[@id=\'menuUsersGroups\']/li/a").click()
    self.driver.find_element(By.XPATH, "//ul[@id=\'menuUsers\']/li[2]/a").click()
    self.driver.find_element(By.ID, "id_0-username").send_keys("ftsadmin1")
    self.driver.find_element(By.ID, "id_0-first_name").send_keys("ftsadmin1 nom")
    self.driver.find_element(By.ID, "id_0-last_name").send_keys("ftsadmin1 ap")
    self.driver.find_element(By.ID, "id_0-email").send_keys("test@test.com")
    self.driver.find_element(By.ID, "id_0-rol").click()
    dropdown = self.driver.find_element(By.ID, "id_0-rol")
    dropdown.find_element(By.XPATH, "//option[. = 'Administrador']").click()
    self.driver.find_element(By.ID, "id_0-password1").click()
    self.driver.find_element(By.ID, "id_0-password1").send_keys("098098ZZZ")
    self.driver.find_element(By.ID, "id_0-password2").send_keys("098098ZZZ")
    self.driver.find_element(By.ID, "id_0-password2").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "filtroUsuarios").click()
    self.driver.find_element(By.ID, "filtroUsuarios").send_keys("ftsadmin1")
    self.driver.find_element(By.ID, "filtroUsuarios").send_keys(Keys.ENTER)
    self.driver.find_element(By.NAME, "edit_profile").click()
    self.driver.find_element(By.ID, "id_registrar").click()
    self.driver.find_element(By.NAME, "search").click()
    self.driver.find_element(By.XPATH, "//ul[@id=\'menuUsers\']/li/a").click()
    self.driver.find_element(By.ID, "filtroUsuarios").click()
    self.driver.find_element(By.ID, "filtroUsuarios").send_keys("ftsadmin1")
    self.driver.find_element(By.ID, "filtroUsuarios").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "dropdownActions").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-6:nth-child(2)").click()
    self.driver.find_element(By.ID, "id_first_name").send_keys("nom1")
    self.driver.find_element(By.ID, "id_last_name").click()
    self.driver.find_element(By.ID, "id_last_name").send_keys("apellido1")
    self.driver.find_element(By.ID, "id_registrar").click()
    self.driver.find_element(By.ID, "filtroUsuarios").click()
    self.driver.find_element(By.ID, "filtroUsuarios").send_keys("ftsadmin1")
    self.driver.find_element(By.ID, "filtroUsuarios").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "dropdownActions").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-danger").click()
    self.driver.find_element(By.CSS_SELECTOR, "h1").click()
    self.driver.find_element(By.XPATH, "//a[contains(@href, \'/accounts/logout/\')]").click()
  
