# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options

class TestSupervisionAgentes():
  def setup_method(self, method):
    chromeOptions = Options()
    self.driver = webdriver.Remote(command_executor='http://172.16.102.101:4444/wd/hub', options=chromeOptions)
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()
  
  def test_supervisionAgentes(self):
    self.driver.get("https://orionis.fts-cloud.net/accounts/login/")
    self.driver.set_window_size(1440, 877)
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("FTS098098OML")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.XPATH, "//a[contains(@href, \'#menuSupervise\')]").click()
    self.driver.find_element(By.XPATH, "//ul[@id=\'menuSupervise\']/li/a").click()
    self.driver.find_element(By.NAME, "tableAgentes_length").click()
    dropdown = self.driver.find_element(By.NAME, "tableAgentes_length")
    dropdown.find_element(By.XPATH, "//option[. = '100']").click()
    self.driver.find_element(By.ID, "filter_group").click()
    dropdown = self.driver.find_element(By.ID, "filter_group")
    dropdown.find_element(By.XPATH, "//option[. = 'FTS_Testing']").click()
    self.driver.find_element(By.ID, "filter_campana").click()
    dropdown = self.driver.find_element(By.ID, "filter_campana")
    dropdown.find_element(By.XPATH, "//option[. = 'MANUAL-TEST']").click()
    self.driver.find_element(By.CSS_SELECTOR, "label > input").click()
    self.driver.find_element(By.CSS_SELECTOR, "label > input").send_keys("test")
    self.driver.find_element(By.CSS_SELECTOR, "label > input").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "textSipStatus").click()
    self.driver.find_element(By.ID, "textSipStatus").click()
    element = self.driver.find_element(By.ID, "textSipStatus")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.XPATH, "//a[contains(@href, \'/accounts/logout/\')]").click()
  
