# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options

class TestVistaModulodeAuditorias():
  def setup_method(self, method):
    chromeOptions = Options()
    self.driver = webdriver.Remote(command_executor='http://172.16.102.101:4444/wd/hub', options=chromeOptions)
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()
  
  def test_vistaModulodeAuditorias(self):
    self.driver.get("https://hablame.fts-cloud.net/accounts/login/")
    self.driver.set_window_size(1050, 721)
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("FTS098098OML")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.XPATH, "//a[contains(@href, \'/auditar_gestion/buscar/1/\')]").click()
    self.driver.find_element(By.ID, "id_fecha").click()
    self.driver.find_element(By.CSS_SELECTOR, "ul > .active").click()
    self.driver.find_element(By.ID, "id_buscar_btn").click()
    self.driver.find_element(By.ID, "check-general").click()
    self.driver.find_element(By.ID, "check-general").click()
    self.driver.find_element(By.ID, "id_fecha").click()
    self.driver.find_element(By.CSS_SELECTOR, "ul:nth-child(1) > li:nth-child(5)").click()
    self.driver.find_element(By.ID, "id_buscar_btn").click()
    self.driver.find_element(By.ID, "select2-id_agente-container").click()
    self.driver.find_element(By.ID, "id_buscar_btn").click()
    self.driver.find_element(By.ID, "check-general").click()
    self.driver.find_element(By.ID, "csvDescarga").click()
    self.driver.find_element(By.ID, "check-mostrar-detalles").click()
    self.driver.find_element(By.ID, "csvDescarga").click()
    self.driver.find_element(By.ID, "id_fecha").click()
    self.driver.find_element(By.CSS_SELECTOR, "ul:nth-child(1) > li:nth-child(6)").click()
    self.driver.find_element(By.ID, "select2-id_agente-container").click()
    self.driver.find_element(By.ID, "id_buscar_btn").click()
    self.driver.find_element(By.XPATH, "//a[contains(@href, \'/accounts/logout/\')]").click()
  
