# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options

class TestSupervisionEntrantesSalientesDialer():
  def setup_method(self, method):
    chromeOptions = Options()
    self.driver = webdriver.Remote(command_executor='http://172.16.102.101:4444/wd/hub', options=chromeOptions)
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()
  
  def test_supervisionEntrantesSalientesDialer(self):
    self.driver.get("https://orionis.fts-cloud.net/accounts/login/")
    self.driver.set_window_size(1440, 877)
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("FTS098098OML")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.XPATH, "//a[contains(@href, \'#menuSupervise\')]").click()
    self.driver.find_element(By.XPATH, "//ul[@id=\'menuSupervise\']/li[2]/a").click()
    self.driver.find_element(By.NAME, "tableEntrantes_length").click()
    dropdown = self.driver.find_element(By.NAME, "tableEntrantes_length")
    dropdown.find_element(By.XPATH, "//option[. = '500']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-entrante:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-entrante:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-entrante:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, "label > input").click()
    self.driver.find_element(By.CSS_SELECTOR, "label > input").send_keys("test")
    self.driver.find_element(By.CSS_SELECTOR, "label > input").send_keys(Keys.ENTER)
    self.driver.find_element(By.XPATH, "//ul[@id=\'menuSupervise\']/li[3]/a").click()
    self.driver.find_element(By.NAME, "tableSalientes_length").click()
    dropdown = self.driver.find_element(By.NAME, "tableSalientes_length")
    dropdown.find_element(By.XPATH, "//option[. = '100']").click()
    self.driver.find_element(By.CSS_SELECTOR, "label > input").click()
    self.driver.find_element(By.CSS_SELECTOR, "label > input").send_keys("test")
    self.driver.find_element(By.CSS_SELECTOR, "label > input").send_keys(Keys.ENTER)
    self.driver.find_element(By.XPATH, "//ul[@id=\'menuSupervise\']/li[4]/a").click()
    self.driver.find_element(By.NAME, "tableDialers_length").click()
    dropdown = self.driver.find_element(By.NAME, "tableDialers_length")
    dropdown.find_element(By.XPATH, "//option[. = '100']").click()
    self.driver.find_element(By.ID, "filter_by_status").click()
    dropdown = self.driver.find_element(By.ID, "filter_by_status")
    dropdown.find_element(By.XPATH, "//option[. = 'Activas']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".row-dialer > th:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".row-dialer > th:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, "label > input").click()
    self.driver.find_element(By.CSS_SELECTOR, "label > input").send_keys("test")
    self.driver.find_element(By.CSS_SELECTOR, "label > input").send_keys(Keys.ENTER)
    self.driver.find_element(By.XPATH, "//a[contains(@href, \'/accounts/logout/\')]").click()
  
