# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options

class TestABMGruposdeAgentes():
  def setup_method(self, method):
    chromeOptions = Options()
    self.driver = webdriver.Remote(command_executor='http://172.16.102.101:4444/wd/hub', options=chromeOptions)
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()
  
  def test_aBMGruposdeAgentes(self):
    self.driver.get("https://orionis.fts-cloud.net/accounts/login/")
    self.driver.set_window_size(1440, 877)
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("FTS098098OML")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.XPATH, "//a[contains(@href, \'#menuUsersGroups\')]").click()
    self.driver.find_element(By.XPATH, "//ul[@id=\'menuUsersGroups\']/li[3]/a").click()
    self.driver.find_element(By.ID, "id_nombre").click()
    self.driver.find_element(By.ID, "id_nombre").send_keys("GtestFTS1")
    self.driver.find_element(By.ID, "id_auto_unpause").click()
    self.driver.find_element(By.ID, "id_auto_unpause").send_keys("15")
    self.driver.find_element(By.ID, "id_conjunto_de_pausa").click()
    self.driver.find_element(By.ID, "id_auto_attend_inbound").click()
    self.driver.find_element(By.ID, "id_obligar_calificacion").click()
    self.driver.find_element(By.ID, "id_acceso_grabaciones_agente").click()
    self.driver.find_element(By.ID, "id_limitar_agendas_personales_en_dias").click()
    self.driver.find_element(By.ID, "id_tiempo_maximo_para_agendar").send_keys("1")
    self.driver.find_element(By.ID, "id_tiempo_maximo_para_agendar").click()
    self.driver.find_element(By.ID, "id_tiempo_maximo_para_agendar").send_keys("2")
    self.driver.find_element(By.ID, "id_tiempo_maximo_para_agendar").click()
    element = self.driver.find_element(By.ID, "id_tiempo_maximo_para_agendar")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "id_acceso_campanas_preview_agente").click()
    self.driver.find_element(By.ID, "id_registrar").click()
    self.driver.find_element(By.CSS_SELECTOR, "#GtestFTS1 #dropdownActions").click()
    self.driver.find_element(By.CSS_SELECTOR, ".show > .dropdown-item:nth-child(2)").click()
    self.driver.find_element(By.ID, "id_nombre").click()
    self.driver.find_element(By.ID, "id_nombre").send_keys("23")
    self.driver.find_element(By.ID, "id_auto_attend_inbound").click()
    self.driver.find_element(By.ID, "id_registrar").click()
    self.driver.find_element(By.CSS_SELECTOR, "#GtestFTS123 #dropdownActions").click()
    self.driver.find_element(By.CSS_SELECTOR, ".show > .dropdown-item:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-danger").click()
    self.driver.find_element(By.NAME, "search").click()
    self.driver.find_element(By.NAME, "search").send_keys("test")
    self.driver.find_element(By.NAME, "search").send_keys(Keys.ENTER)
    self.driver.find_element(By.XPATH, "//a[contains(@href, \'/accounts/logout/\')]").click()
  
