# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options

class TestSeguridadAuditoria():
  def setup_method(self, method):
    chromeOptions = Options()
    self.driver = webdriver.Remote(command_executor='http://172.16.102.101:4444/wd/hub', options=chromeOptions)
    self.vars = {} 
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_seguridadAuditoria(self):
    self.driver.get("https://hablame.fts-cloud.net/accounts/login/")
    self.driver.set_window_size(1050, 721)
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("FTS098098OML")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.XPATH, "//a[contains(@href, \'#menuSeguridad\')]").click()
    self.driver.find_element(By.XPATH, "//ul[@id=\'menuSeguridad\']/li/a").click()
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.ID, "range").click()
    self.driver.find_element(By.CSS_SELECTOR, ".p-datepicker-prev").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".p-datepicker-prev")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > td:nth-child(7) > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".p-datepicker-next-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".p-datepicker-today > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".p-toolbar-group-right > .p-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".p-sortable-column:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".p-sortable-column:nth-child(6) > .p-column-header-content").click()
    self.driver.find_element(By.CSS_SELECTOR, ".pi-sort-amount-up-alt").click()
    self.driver.find_element(By.CSS_SELECTOR, ".p-button-info > .p-button-label").click()
    self.driver.switch_to.default_content()
    self.driver.find_element(By.XPATH, "//a[contains(@href, \'/accounts/logout/\')]").click()
  
