[general]
mailboxdetail=yes
tos=ef
Language=es
disallow=all
allow=ulaw
allow=alaw
allow=gsm

[100]
deny=0.0.0.0/0.0.0.0
secret=omnileads
transfer=yes
host=dynamic
type=friend
port=4569
qualify=yes
permit=0.0.0.0/0.0.0.0
requirecalltoken=yes
context=omnileads
setvar=REALCALLERIDNUM=1234567890
callerid=<1234567890>

[1234567]
deny=0.0.0.0/0.0.0.0
secret=omnileads
transfer=yes
host=dynamic
type=friend
port=4569
qualify=yes
permit=0.0.0.0/0.0.0.0
requirecalltoken=yes
context=omnileads
setvar=REALCALLERIDNUM=1234567891
callerid=<1234567891>