[omnileads](!)
type=wizard
accepts_registrations=no
accepts_auth=no
sends_registrations=no
sends_auth=no
endpoint/disallow=all
endpoint/allow=alaw,ulaw,gsm
endpoint/direct_media=no
endpoint/force_rport=yes
endpoint/ice_support=no
endpoint/moh_suggest=default
endpoint/send_rpid=yes
endpoint/rewrite_contact=yes
endpoint/send_pai=yes
endpoint/allow_transfer=yes
endpoint/trust_id_inbound=yes
endpoint/device_state_busy_at=1
endpoint/trust_id_outbound=yes
endpoint/send_diversion=yes
endpoint/rtp_symmetric=yes
endpoint/rtp_keepalive=25
endpoint/rtp_timeout=30
endpoint/rtp_timeout_hold=360
endpoint/dtmf_mode=rfc4733
endpoint/context=omnileads
aor/authenticate_qualify=no
aor/max_contacts=2
aor/remove_existing=yes
aor/minimum_expiration=30
aor/maximum_expiration=60
aor/qualify_frequency=30
aor/support_path=yes
transport=udp-transport
identify/match=acd-server
identify/srv_lookups=yes
aor/contact=sip:acd-server:5060
remote_hosts=acd-server:5060
aor/authenticate_qualify=no 

;Trunk Dialer Asterisk Host
[voicebot]
type=wizard
accepts_registrations=no
accepts_auth=no
sends_registrations=no
sends_auth=no
transport=udp-transport
endpoint/disallow=all
endpoint/allow=alaw,ulaw,gsm
endpoint/direct_media=no
endpoint/force_rport=yes
endpoint/context=omnileads
endpoint/direct_media=no
endpoint/trust_id_inbound=yes
endpoint/trust_id_outbound=yes
endpoint/trust_id_inbound=yes
endpoint/identify_by=ip
identify/match=acd-server
identify/srv_lookups=yes
aor/contact=sip:acd-server:5060
aor/authenticate_qualify=no 
remote_hosts=acd-server:5060
endpoint/allow_transfer=yes


;Trunk ACD Asterisk Host
[01177660010](omnileads)
inbound_auth/username=01177660010

;Trunk Dialer Asterisk Host
[01177660020](omnileads)
inbound_auth/username=01177660020

;Trunk DevOps Asterisk Host
[99999999](omnileads)
inbound_auth/username=99999999

; SIPP command line tool trunk
[sipp](omnileads)
transport=udp-transport
accepts_registrations=no
accepts_auth=no
endpoint/allow=all

;OML Trunks X0X0X0X0
[40404040](omnileads)
inbound_auth/username=40404040

[50505050](omnileads)
inbound_auth/username=50505050

[60606060](omnileads)
inbound_auth/username=60606060

[70707070](omnileads)
inbound_auth/username=70707070
