server {
	listen 8888;
	server_name localhost;
	location / {
		root /usr/share/backendCGI/;
		index main.html;
	}

	location /shell {
		root /usr/share/backendCGI;
		gzip off;
		include fastcgi_params;
		fastcgi_pass unix:/var/run/fcgiwrap.socket;
		fastcgi_param SCRIPT_FILENAME /usr/share/backendCGI$fastcgi_script_name;
	}

	location /generate_inbounds.cgi {
		root /usr/share/backendCGI;
		gzip off;
		include fastcgi_params;
		fastcgi_pass unix:/var/run/fcgiwrap.socket;
		fastcgi_param SCRIPT_FILENAME /usr/share/backendCGI$fastcgi_script_name;
	}

	location /reset_tables_script.cgi {
		root /usr/share/backendCGI;
		gzip off;
		include fastcgi_params;
		fastcgi_pass unix:/var/run/fcgiwrap.socket;
		fastcgi_param SCRIPT_FILENAME /usr/share/backendCGI$fastcgi_script_name;
	}
}
